from geoplan_bench.agents.EarthAgent import EarthAgent
from geoplan_bench.agents.Plan_and_Execute import PlanExecuteAgent
from geoplan_bench.agents.ReAct import ReActAgent
from geoplan_bench.agents.CoT import ZeroShotCoTBasedAgent
from geoplan_bench.agents.Debate import DebateAgent
from geoplan_bench.agents.AFlow import AFlowAgent
from geoplan_bench.tools import *
import os
from dotenv import load_dotenv
load_dotenv()


def create_earth_agent(model="gpt-4o-mini",api_key=os.getenv("OPENAI_API_KEY"),base_url=os.getenv("OPENAI_API_BASE")):
    earth_agent = EarthAgent(model=model,api_key=api_key,base_url=base_url)
    dataFetcherAgent = ReActAgent(
        name="dataFetcher",
        description="Remote sensing data acquisition expert, responsible for acquiring remote sensing imagery data from various satellite platforms, sensors and data sources, including optical, radar, hyperspectral and other types of remote sensing data",
        max_steps=3,
        system_prompt="Your role is to fetch remote sensing data to complete the final task. Various tools are provided to you, you can choose to use them to do something such as download satellite images or recommend satellite platforms.",
        temperature=0.0
    )
    dataFetcherAgent.add_tool(download_satellite_imagery)
    dataFetcherAgent.add_tool(download_file)
    dataFetcherAgent.add_tool(web_search)
    dataFetcherAgent.add_tool(get_weather_data)
    dataFetcherAgent.add_tool(read_database)
    dataFetcherAgent.add_tool(get_current_time)
    dataFetcherAgent.add_tool(recommend_satellite_platforms)
    dataFetcherAgent.add_tool(suggest_processing_workflows)
    dataFetcherAgent.add_tool(explain_remote_sensing_concepts)
    preprocessingAgent = ReActAgent(
        name="preprocessing",
        description="Remote sensing data preprocessing expert, responsible for atmospheric correction, geometric correction, radiometric calibration, noise removal and other preprocessing operations on raw remote sensing data to ensure data quality",
        max_steps=3,
        system_prompt="Your role is to preprocess remote sensing data to complete the final task. Various tools are provided to you, you can choose to use them to do something such as atmospheric correction, cloud mask removal or geometric correction.",
        temperature=0.0
    )
    preprocessingAgent.add_tool(atmospheric_correction)
    preprocessingAgent.add_tool(geometric_correction)
    preprocessingAgent.add_tool(cloud_mask_removal)
    preprocessingAgent.add_tool(band_combination)
    preprocessingAgent.add_tool(resize_image)
    preprocessingAgent.add_tool(statistical_analysis)
    preprocessingAgent.add_tool(format_data)
    preprocessingAgent.add_tool(extract_image_metadata)
    objectDetectorAgent = ReActAgent(
        name="objectDetector",
        description="Remote sensing object detection expert, specialized in detecting and identifying various ground targets in remote sensing imagery, such as buildings, roads, vehicles, ships and other artificial targets",
        max_steps=2,
        temperature=0.0
    )
    objectDetectorAgent.add_tool(detect_buildings)
    objectDetectorAgent.add_tool(detect_roads)
    objectDetectorAgent.add_tool(detect_vehicles)
    objectDetectorAgent.add_tool(detect_ships)
    objectDetectorAgent.add_tool(crop_image)
    objectDetectorAgent.add_tool(extract_image_metadata)
    objectDetectorAgent.add_tool(statistical_analysis)
    objectDetectorAgent.add_tool(format_data)
    semanticSegmentorAgent = ReActAgent(
        name="semanticSegmentor",
        description="Remote sensing semantic segmentation expert, perform pixel-level classification of remote sensing imagery, identify different land use types and ground cover, generate accurate land cover maps",
        max_steps=2,
        temperature=0.0
    )
    semanticSegmentorAgent.add_tool(classify_land_cover)
    semanticSegmentorAgent.add_tool(segment_vegetation)
    semanticSegmentorAgent.add_tool(segment_water_bodies)
    semanticSegmentorAgent.add_tool(segment_urban_areas)
    instanceSegmentorAgent = ReActAgent(
        name="instanceSegmentor",
        description="Remote sensing instance segmentation expert, further distinguish different instances of the same type of targets based on semantic segmentation, such as distinguishing different building individuals, farmland plots, etc.",
        max_steps=2,
        temperature=0.0
    )
    instanceSegmentorAgent.add_tool(segment_individual_buildings)
    instanceSegmentorAgent.add_tool(segment_agricultural_fields)
    sceneClassifierAgent = ReActAgent(
        name="sceneClassifier",
        description="Remote sensing scene classification expert, perform overall scene understanding and classification of remote sensing imagery, identify different geographical environment types and landscape features",
        max_steps=2,
        temperature=0.0
    )
    sceneClassifierAgent.add_tool(classify_landscape_type)
    sceneClassifierAgent.add_tool(classify_terrain_type)
    sceneClassifierAgent.add_tool(assess_urbanization_level)
    imageGeneratorAgent = ReActAgent(
        name="imageGenerator",
        description="Remote sensing image generation expert, generate high-quality remote sensing imagery based on existing remote sensing data, including super-resolution reconstruction, cloud removal, multi-temporal fusion, etc.",
        max_steps=1,
        temperature=0.0
    )
    imageGeneratorAgent.add_tool(enhance_image_resolution)
    changeDetectorAgent = ReActAgent(
        name="changeDetector",
        description="Remote sensing change detection expert, detect and analyze surface changes by comparing remote sensing imagery from different periods, monitor urban expansion, deforestation, disaster impacts, etc.",
        max_steps=2,
        temperature=0.0
    )
    changeDetectorAgent.add_tool(detect_urban_expansion)
    changeDetectorAgent.add_tool(monitor_deforestation)
    changeDetectorAgent.add_tool(assess_disaster_damage)
    generalChatBotAgent = ReActAgent(
        name="generalChatBot",
        description="General remote sensing consultant expert, providing professional consultation and Q&A services related to remote sensing technology, explaining remote sensing concepts, analyzing remote sensing application scenarios",
        system_prompt="You are a remote sensing technology expert who can answer various remote sensing related questions and provide professional technical consultation and application suggestions.",
        temperature=0.0
    )
    generalChatBotAgent.add_tool(explain_remote_sensing_concepts)
    generalChatBotAgent.add_tool(recommend_satellite_platforms)
    generalChatBotAgent.add_tool(suggest_processing_workflows)
    generalChatBotAgent.add_tool(provide_technical_guidance)
    generalChatBotAgent.add_tool(translate_text)
    generalChatBotAgent.add_tool(summarize_text)
    generalChatBotAgent.add_tool(extract_keywords)
    generalChatBotAgent.add_tool(format_data)
    generalChatBotAgent.add_tool(generate_analysis_reports)
    generalChatBotAgent.add_tool(statistical_analysis)
    agriScoutAgent = ReActAgent(
        name="agriScout",
        max_steps=5,
        description="Agricultural remote sensing expert, utilizing remote sensing technology for precision agriculture applications, including crop monitoring, yield prediction, pest detection, irrigation management and other full-process agricultural production services",
        system_prompt="You are an agricultural remote sensing expert, focusing on using remote sensing technology to solve various problems in agricultural production and providing precision agriculture solutions.",
        temperature=0.0
    )
    agriScoutAgent.add_tool(monitor_crop_health)
    agriScoutAgent.add_tool(predict_crop_yield)
    agriScoutAgent.add_tool(detect_plant_diseases)
    agriScoutAgent.add_tool(assess_soil_moisture)
    agriScoutAgent.add_tool(optimize_irrigation_schedule)
    agriScoutAgent.add_tool(assess_pasture_quality)
    agriScoutAgent.add_tool(predict_harvest_timing)
    agriScoutAgent.add_tool(get_weather_data)
    agriScoutAgent.add_tool(statistical_analysis)
    agriScoutAgent.add_tool(linear_regression)
    agriScoutAgent.add_tool(correlation_analysis)
    agriScoutAgent.add_tool(get_current_time)
    agriScoutAgent.add_tool(format_data)
    agriScoutAgent.add_tool(generate_analysis_reports)
    crisisCommanderAgent = ReActAgent(
        name="crisisCommander",
        max_steps=5,
        description="Disaster emergency remote sensing expert, utilizing remote sensing technology for disaster monitoring, risk assessment, emergency response and post-disaster reconstruction assessment, providing scientific decision support for disaster prevention and mitigation",
        system_prompt="You are a disaster emergency remote sensing expert, specializing in using remote sensing technology for disaster monitoring and emergency management, providing technical support for disaster prevention and control.",
        temperature=0.0
    )
    crisisCommanderAgent.add_tool(monitor_flood_extent)
    crisisCommanderAgent.add_tool(track_wildfire_progression)
    crisisCommanderAgent.add_tool(assess_earthquake_damage)
    crisisCommanderAgent.add_tool(predict_landslide_risk)
    crisisCommanderAgent.add_tool(monitor_drought_conditions)
    crisisCommanderAgent.add_tool(evaluate_infrastructure_damage)
    crisisCommanderAgent.add_tool(assess_recovery_progress)
    crisisCommanderAgent.add_tool(generate_analysis_reports)
    crisisCommanderAgent.add_tool(format_data)
    crisisCommanderAgent.add_tool(statistical_analysis)
    urbanistAIAgent = ReActAgent(
        name="urbanistAI",
        max_steps=5,
        description="Urban planning remote sensing expert, utilizing remote sensing technology for urban development monitoring, land use planning, traffic analysis, environmental assessment and other urban planning and management work",
        system_prompt="You are an urban planning remote sensing expert, specializing in using remote sensing technology for urban analysis and planning, providing data support for smart city construction.",
        temperature=0.0
    )
    urbanistAIAgent.add_tool(analyze_urban_growth_patterns)
    urbanistAIAgent.add_tool(assess_land_use_efficiency)
    urbanistAIAgent.add_tool(monitor_traffic_congestion)
    urbanistAIAgent.add_tool(evaluate_green_space_distribution)
    urbanistAIAgent.add_tool(assess_air_quality_patterns)
    urbanistAIAgent.add_tool(analyze_population_density)
    urbanistAIAgent.add_tool(evaluate_urban_heat_island)
    urbanistAIAgent.add_tool(assess_flood_risk_zones)
    urbanistAIAgent.add_tool(statistical_analysis)
    urbanistAIAgent.add_tool(correlation_analysis)
    urbanistAIAgent.add_tool(convert_coordinates)
    urbanistAIAgent.add_tool(format_data)
    urbanistAIAgent.add_tool(read_database)
    urbanistAIAgent.add_tool(generate_analysis_reports)
    environmentalistAgent = ReActAgent(
        name="environmentalist",
        max_steps=5,
        description="Environmental remote sensing monitoring expert, utilizing remote sensing technology for environmental quality monitoring, ecosystem assessment, pollution source identification, environmental change tracking and other environmental protection work",
        system_prompt="You are an environmental remote sensing expert, focusing on using remote sensing technology for environmental monitoring and ecological protection, providing scientific basis for environmental management.",
        temperature=0.0
    )
    environmentalistAgent.add_tool(monitor_air_pollution)
    environmentalistAgent.add_tool(assess_water_quality)
    environmentalistAgent.add_tool(track_biodiversity_changes)
    environmentalistAgent.add_tool(monitor_forest_health)
    environmentalistAgent.add_tool(detect_illegal_logging)
    environmentalistAgent.add_tool(assess_wetland_conditions)
    environmentalistAgent.add_tool(evaluate_ecosystem_services)
    environmentalistAgent.add_tool(assess_carbon_sequestration)
    environmentalistAgent.add_tool(generate_analysis_reports)
    environmentalistAgent.add_tool(format_data)
    geologistAgent = ReActAgent(
        name="geologist",
        max_steps=5,
        description="Geological remote sensing expert, utilizing remote sensing technology for geological structure analysis, mineral resource exploration, geological hazard assessment, topographic and geomorphological research and other geological science applications",
        system_prompt="You are a geological remote sensing expert, specializing in using remote sensing technology for geological research and resource exploration, providing technical support for geological science research.",
        temperature=0.0
    )
    geologistAgent.add_tool(analyze_geological_structures)
    geologistAgent.add_tool(identify_mineral_deposits)
    geologistAgent.add_tool(assess_slope_stability)
    geologistAgent.add_tool(map_fault_systems)
    geologistAgent.add_tool(evaluate_groundwater_resources)
    geologistAgent.add_tool(assess_volcanic_activity)
    geologistAgent.add_tool(generate_analysis_reports)
    geologistAgent.add_tool(format_data)
    geologistAgent.add_tool(statistical_analysis)
    minerAgent = ReActAgent(
        name="miner",
        max_steps=5,
        description="Mining remote sensing expert, utilizing remote sensing technology for mineral resource exploration, mining monitoring, environmental impact assessment, mining area reclamation supervision and other full-process mining management",
        system_prompt="You are a mining remote sensing expert, specializing in using remote sensing technology for mineral exploration and mining supervision, providing technical guarantee for sustainable mining development.",
        temperature=0.0
    )
    minerAgent.add_tool(explore_mineral_resources)
    minerAgent.add_tool(monitor_mining_operations)
    minerAgent.add_tool(assess_environmental_impact)
    minerAgent.add_tool(evaluate_ore_quality)
    minerAgent.add_tool(assess_mining_safety)
    minerAgent.add_tool(generate_analysis_reports)
    minerAgent.add_tool(format_data)
    minerAgent.add_tool(statistical_analysis)
    oceanographerAgent = ReActAgent(
        name="oceanographer",
        max_steps=5,
        description="Marine remote sensing expert, utilizing remote sensing technology for marine environment monitoring, marine resource investigation, marine disaster warning, marine ecological assessment and other marine science research",
        system_prompt="You are a marine remote sensing expert, specializing in using remote sensing technology for marine research and monitoring, providing data support for marine science and marine management.",
        temperature=0.0
    )
    oceanographerAgent.add_tool(monitor_sea_surface_temperature)
    oceanographerAgent.add_tool(track_ocean_currents)
    oceanographerAgent.add_tool(assess_marine_pollution)
    oceanographerAgent.add_tool(assess_coastal_erosion)
    oceanographerAgent.add_tool(evaluate_fishing_grounds)
    oceanographerAgent.add_tool(get_weather_data)
    oceanographerAgent.add_tool(statistical_analysis)
    oceanographerAgent.add_tool(linear_regression)
    oceanographerAgent.add_tool(convert_coordinates)
    oceanographerAgent.add_tool(format_data)
    oceanographerAgent.add_tool(get_current_time)
    oceanographerAgent.add_tool(generate_analysis_reports)
    defenseSecurityAgent = ReActAgent(
        name="defenseSecurity",
        max_steps=5,
        description="Defense and security remote sensing expert, utilizing remote sensing technology for military facility monitoring, border security surveillance, strategic infrastructure assessment, threat analysis and other national defense and security applications",
        system_prompt="You are a defense and security remote sensing expert, specializing in using remote sensing technology for national defense and security monitoring and analysis, providing technical support for national security.",
        temperature=0.0
    )
    defenseSecurityAgent.add_tool(detect_military_facilities)
    defenseSecurityAgent.add_tool(monitor_border_security)
    defenseSecurityAgent.add_tool(assess_strategic_infrastructure)
    defenseSecurityAgent.add_tool(track_vessel_activities)
    defenseSecurityAgent.add_tool(monitor_airspace_violations)
    defenseSecurityAgent.add_tool(analyze_threat_patterns)
    defenseSecurityAgent.add_tool(assess_force_deployment)
    defenseSecurityAgent.add_tool(evaluate_operational_readiness)
    defenseSecurityAgent.add_tool(statistical_analysis)
    defenseSecurityAgent.add_tool(correlation_analysis)
    defenseSecurityAgent.add_tool(convert_coordinates)
    defenseSecurityAgent.add_tool(format_data)
    defenseSecurityAgent.add_tool(read_database)
    defenseSecurityAgent.add_tool(get_current_time)
    defenseSecurityAgent.add_tool(generate_analysis_reports)
    earth_agent.add_agent(1, dataFetcherAgent)
    earth_agent.add_agent(1, preprocessingAgent)
    earth_agent.add_agent(2, objectDetectorAgent)
    earth_agent.add_agent(2, semanticSegmentorAgent)
    earth_agent.add_agent(2, instanceSegmentorAgent)
    earth_agent.add_agent(2, sceneClassifierAgent)
    earth_agent.add_agent(2, imageGeneratorAgent)
    earth_agent.add_agent(2, changeDetectorAgent)
    earth_agent.add_agent(3, generalChatBotAgent)
    earth_agent.add_agent(3, agriScoutAgent)
    earth_agent.add_agent(3, crisisCommanderAgent)
    earth_agent.add_agent(3, urbanistAIAgent)
    earth_agent.add_agent(3, environmentalistAgent)
    earth_agent.add_agent(3, geologistAgent)
    earth_agent.add_agent(3, minerAgent)
    earth_agent.add_agent(3, oceanographerAgent)
    earth_agent.add_agent(3, defenseSecurityAgent)
    return earth_agent
    
def create_plan_and_execute_agent():
    plan_and_execute_agent = PlanExecuteAgent()
    plan_and_execute_agent.add_tool(download_file)
    plan_and_execute_agent.add_tool(web_search)
    plan_and_execute_agent.add_tool(get_weather_data)
    plan_and_execute_agent.add_tool(statistical_analysis)
    plan_and_execute_agent.add_tool(linear_regression)
    plan_and_execute_agent.add_tool(correlation_analysis)
    plan_and_execute_agent.add_tool(convert_coordinates)
    plan_and_execute_agent.add_tool(format_data)
    plan_and_execute_agent.add_tool(read_database)
    plan_and_execute_agent.add_tool(get_current_time)
    plan_and_execute_agent.add_tool(calculate_time_difference)
    plan_and_execute_agent.add_tool(extract_keywords)
    plan_and_execute_agent.add_tool(translate_text)
    plan_and_execute_agent.add_tool(summarize_text)
    plan_and_execute_agent.add_tool(resize_image)
    plan_and_execute_agent.add_tool(crop_image)
    plan_and_execute_agent.add_tool(extract_image_metadata)
    plan_and_execute_agent.add_tool(download_satellite_imagery)
    plan_and_execute_agent.add_tool(atmospheric_correction)
    plan_and_execute_agent.add_tool(geometric_correction)
    plan_and_execute_agent.add_tool(cloud_mask_removal)
    plan_and_execute_agent.add_tool(band_combination)
    plan_and_execute_agent.add_tool(detect_buildings)
    plan_and_execute_agent.add_tool(detect_roads)
    plan_and_execute_agent.add_tool(detect_vehicles)
    plan_and_execute_agent.add_tool(detect_ships)
    plan_and_execute_agent.add_tool(classify_land_cover)
    plan_and_execute_agent.add_tool(segment_vegetation)
    plan_and_execute_agent.add_tool(segment_water_bodies)
    plan_and_execute_agent.add_tool(segment_urban_areas)
    plan_and_execute_agent.add_tool(segment_individual_buildings)
    plan_and_execute_agent.add_tool(segment_agricultural_fields)
    plan_and_execute_agent.add_tool(classify_landscape_type)
    plan_and_execute_agent.add_tool(classify_terrain_type)
    plan_and_execute_agent.add_tool(assess_urbanization_level)
    plan_and_execute_agent.add_tool(enhance_image_resolution)
    plan_and_execute_agent.add_tool(detect_urban_expansion)
    plan_and_execute_agent.add_tool(monitor_deforestation)
    plan_and_execute_agent.add_tool(assess_disaster_damage)
    plan_and_execute_agent.add_tool(explain_remote_sensing_concepts)
    plan_and_execute_agent.add_tool(recommend_satellite_platforms)
    plan_and_execute_agent.add_tool(suggest_processing_workflows)
    plan_and_execute_agent.add_tool(provide_technical_guidance)
    plan_and_execute_agent.add_tool(monitor_crop_health)
    plan_and_execute_agent.add_tool(predict_crop_yield)
    plan_and_execute_agent.add_tool(detect_plant_diseases)
    plan_and_execute_agent.add_tool(assess_soil_moisture)
    plan_and_execute_agent.add_tool(optimize_irrigation_schedule)
    plan_and_execute_agent.add_tool(assess_pasture_quality)
    plan_and_execute_agent.add_tool(predict_harvest_timing)
    plan_and_execute_agent.add_tool(analyze_farming_patterns)
    plan_and_execute_agent.add_tool(monitor_flood_extent)
    plan_and_execute_agent.add_tool(track_wildfire_progression)
    plan_and_execute_agent.add_tool(assess_earthquake_damage)
    plan_and_execute_agent.add_tool(predict_landslide_risk)
    plan_and_execute_agent.add_tool(monitor_drought_conditions)
    plan_and_execute_agent.add_tool(evaluate_infrastructure_damage)
    plan_and_execute_agent.add_tool(plan_evacuation_routes)
    plan_and_execute_agent.add_tool(assess_recovery_progress)
    plan_and_execute_agent.add_tool(analyze_urban_growth_patterns)
    plan_and_execute_agent.add_tool(assess_land_use_efficiency)
    plan_and_execute_agent.add_tool(monitor_traffic_congestion)
    plan_and_execute_agent.add_tool(evaluate_green_space_distribution)
    plan_and_execute_agent.add_tool(assess_air_quality_patterns)
    plan_and_execute_agent.add_tool(analyze_population_density)
    plan_and_execute_agent.add_tool(evaluate_urban_heat_island)
    plan_and_execute_agent.add_tool(assess_flood_risk_zones)
    plan_and_execute_agent.add_tool(monitor_air_pollution)
    plan_and_execute_agent.add_tool(assess_water_quality)
    plan_and_execute_agent.add_tool(track_biodiversity_changes)
    plan_and_execute_agent.add_tool(monitor_forest_health)
    plan_and_execute_agent.add_tool(detect_illegal_logging)
    plan_and_execute_agent.add_tool(assess_wetland_conditions)
    plan_and_execute_agent.add_tool(evaluate_ecosystem_services)
    plan_and_execute_agent.add_tool(assess_carbon_sequestration)
    plan_and_execute_agent.add_tool(analyze_geological_structures)
    plan_and_execute_agent.add_tool(identify_mineral_deposits)
    plan_and_execute_agent.add_tool(assess_slope_stability)
    plan_and_execute_agent.add_tool(map_fault_systems)
    plan_and_execute_agent.add_tool(evaluate_groundwater_resources)
    plan_and_execute_agent.add_tool(assess_volcanic_activity)
    plan_and_execute_agent.add_tool(explore_mineral_resources)
    plan_and_execute_agent.add_tool(monitor_mining_operations)
    plan_and_execute_agent.add_tool(assess_environmental_impact)
    plan_and_execute_agent.add_tool(track_land_reclamation)
    plan_and_execute_agent.add_tool(evaluate_ore_quality)
    plan_and_execute_agent.add_tool(assess_mining_safety)
    plan_and_execute_agent.add_tool(monitor_sea_surface_temperature)
    plan_and_execute_agent.add_tool(track_ocean_currents)
    plan_and_execute_agent.add_tool(assess_marine_pollution)
    plan_and_execute_agent.add_tool(monitor_algae_blooms)
    plan_and_execute_agent.add_tool(track_ship_movements)
    plan_and_execute_agent.add_tool(assess_coastal_erosion)
    plan_and_execute_agent.add_tool(monitor_ice_coverage)
    plan_and_execute_agent.add_tool(evaluate_fishing_grounds)
    plan_and_execute_agent.add_tool(detect_military_facilities)
    plan_and_execute_agent.add_tool(monitor_border_security)
    plan_and_execute_agent.add_tool(assess_strategic_infrastructure)
    plan_and_execute_agent.add_tool(track_vessel_activities)
    plan_and_execute_agent.add_tool(monitor_airspace_violations)
    plan_and_execute_agent.add_tool(analyze_threat_patterns)
    plan_and_execute_agent.add_tool(assess_force_deployment)
    plan_and_execute_agent.add_tool(evaluate_operational_readiness)
    return plan_and_execute_agent

def create_react_agent(temperature=0.2,model="gpt-4o-mini",api_key=os.getenv("OPENAI_API_KEY"),base_url=os.getenv("OPENAI_API_BASE")):
    react_agent = ReActAgent(model=model,api_key=api_key,base_url=base_url)
    react_agent.add_tool(download_file)
    react_agent.add_tool(web_search)
    react_agent.add_tool(get_weather_data)
    react_agent.add_tool(statistical_analysis)
    react_agent.add_tool(linear_regression)
    react_agent.add_tool(correlation_analysis)
    react_agent.add_tool(convert_coordinates)
    react_agent.add_tool(format_data)
    react_agent.add_tool(read_database)
    react_agent.add_tool(get_current_time)
    react_agent.add_tool(calculate_time_difference)
    react_agent.add_tool(extract_keywords)
    react_agent.add_tool(translate_text)
    react_agent.add_tool(summarize_text)
    react_agent.add_tool(resize_image)
    react_agent.add_tool(crop_image)
    react_agent.add_tool(extract_image_metadata)
    react_agent.add_tool(generate_analysis_reports)
    react_agent.add_tool(download_satellite_imagery)
    react_agent.add_tool(atmospheric_correction)
    react_agent.add_tool(geometric_correction)
    react_agent.add_tool(cloud_mask_removal)
    react_agent.add_tool(band_combination)
    react_agent.add_tool(detect_buildings)
    react_agent.add_tool(detect_roads)
    react_agent.add_tool(detect_vehicles)
    react_agent.add_tool(detect_ships)
    react_agent.add_tool(classify_land_cover)
    react_agent.add_tool(segment_vegetation)
    react_agent.add_tool(segment_water_bodies)
    react_agent.add_tool(segment_urban_areas)
    react_agent.add_tool(segment_individual_buildings)
    react_agent.add_tool(segment_agricultural_fields)
    react_agent.add_tool(classify_landscape_type)
    react_agent.add_tool(classify_terrain_type)
    react_agent.add_tool(assess_urbanization_level)
    react_agent.add_tool(enhance_image_resolution)
    react_agent.add_tool(detect_urban_expansion)
    react_agent.add_tool(monitor_deforestation)
    react_agent.add_tool(assess_disaster_damage)
    react_agent.add_tool(explain_remote_sensing_concepts)
    react_agent.add_tool(recommend_satellite_platforms)
    react_agent.add_tool(suggest_processing_workflows)
    react_agent.add_tool(provide_technical_guidance)
    react_agent.add_tool(monitor_crop_health)
    react_agent.add_tool(predict_crop_yield)
    react_agent.add_tool(detect_plant_diseases)
    react_agent.add_tool(assess_soil_moisture)
    react_agent.add_tool(optimize_irrigation_schedule)
    react_agent.add_tool(assess_pasture_quality)
    react_agent.add_tool(predict_harvest_timing)
    react_agent.add_tool(analyze_farming_patterns)
    react_agent.add_tool(monitor_flood_extent)
    react_agent.add_tool(track_wildfire_progression)
    react_agent.add_tool(assess_earthquake_damage)
    react_agent.add_tool(predict_landslide_risk)
    react_agent.add_tool(monitor_drought_conditions)
    react_agent.add_tool(evaluate_infrastructure_damage)
    react_agent.add_tool(plan_evacuation_routes)
    react_agent.add_tool(assess_recovery_progress)
    react_agent.add_tool(analyze_urban_growth_patterns)
    react_agent.add_tool(assess_land_use_efficiency)
    react_agent.add_tool(monitor_traffic_congestion)
    react_agent.add_tool(evaluate_green_space_distribution)
    react_agent.add_tool(assess_air_quality_patterns)
    react_agent.add_tool(analyze_population_density)
    react_agent.add_tool(evaluate_urban_heat_island)
    react_agent.add_tool(assess_flood_risk_zones)
    react_agent.add_tool(monitor_air_pollution)
    react_agent.add_tool(assess_water_quality)
    react_agent.add_tool(track_biodiversity_changes)
    react_agent.add_tool(monitor_forest_health)
    react_agent.add_tool(detect_illegal_logging)
    react_agent.add_tool(assess_wetland_conditions)
    react_agent.add_tool(evaluate_ecosystem_services)
    react_agent.add_tool(assess_carbon_sequestration)
    react_agent.add_tool(analyze_geological_structures)
    react_agent.add_tool(identify_mineral_deposits)
    react_agent.add_tool(assess_slope_stability)
    react_agent.add_tool(map_fault_systems)
    react_agent.add_tool(evaluate_groundwater_resources)
    react_agent.add_tool(assess_volcanic_activity)
    react_agent.add_tool(explore_mineral_resources)
    react_agent.add_tool(monitor_mining_operations)
    react_agent.add_tool(assess_environmental_impact)
    react_agent.add_tool(track_land_reclamation)
    react_agent.add_tool(evaluate_ore_quality)
    react_agent.add_tool(assess_mining_safety)
    react_agent.add_tool(monitor_sea_surface_temperature)
    react_agent.add_tool(track_ocean_currents)
    react_agent.add_tool(assess_marine_pollution)
    react_agent.add_tool(monitor_algae_blooms)
    react_agent.add_tool(track_ship_movements)
    react_agent.add_tool(assess_coastal_erosion)
    react_agent.add_tool(monitor_ice_coverage)
    react_agent.add_tool(evaluate_fishing_grounds)
    react_agent.add_tool(detect_military_facilities)
    react_agent.add_tool(monitor_border_security)
    react_agent.add_tool(assess_strategic_infrastructure)
    react_agent.add_tool(track_vessel_activities)
    react_agent.add_tool(monitor_airspace_violations)
    react_agent.add_tool(analyze_threat_patterns)
    react_agent.add_tool(assess_force_deployment)
    react_agent.add_tool(evaluate_operational_readiness)
    react_agent.temperature = temperature
    return react_agent

def create_zero_shot_cot_based_agent():
    zero_shot_cot_based_agent = ZeroShotCoTBasedAgent()
    zero_shot_cot_based_agent.add_tool(download_file)
    zero_shot_cot_based_agent.add_tool(web_search)
    zero_shot_cot_based_agent.add_tool(get_weather_data)
    zero_shot_cot_based_agent.add_tool(statistical_analysis)
    zero_shot_cot_based_agent.add_tool(linear_regression)
    zero_shot_cot_based_agent.add_tool(correlation_analysis)
    zero_shot_cot_based_agent.add_tool(convert_coordinates)
    zero_shot_cot_based_agent.add_tool(format_data)
    zero_shot_cot_based_agent.add_tool(read_database)
    zero_shot_cot_based_agent.add_tool(get_current_time)
    zero_shot_cot_based_agent.add_tool(calculate_time_difference)
    zero_shot_cot_based_agent.add_tool(extract_keywords)
    zero_shot_cot_based_agent.add_tool(translate_text)
    zero_shot_cot_based_agent.add_tool(summarize_text)
    zero_shot_cot_based_agent.add_tool(resize_image)
    zero_shot_cot_based_agent.add_tool(crop_image)
    zero_shot_cot_based_agent.add_tool(extract_image_metadata)
    zero_shot_cot_based_agent.add_tool(download_satellite_imagery)
    zero_shot_cot_based_agent.add_tool(atmospheric_correction)
    zero_shot_cot_based_agent.add_tool(geometric_correction)
    zero_shot_cot_based_agent.add_tool(cloud_mask_removal)
    zero_shot_cot_based_agent.add_tool(band_combination)
    zero_shot_cot_based_agent.add_tool(detect_buildings)
    zero_shot_cot_based_agent.add_tool(detect_roads)
    zero_shot_cot_based_agent.add_tool(detect_vehicles)
    zero_shot_cot_based_agent.add_tool(detect_ships)
    zero_shot_cot_based_agent.add_tool(classify_land_cover)
    zero_shot_cot_based_agent.add_tool(segment_vegetation)
    zero_shot_cot_based_agent.add_tool(segment_water_bodies)
    zero_shot_cot_based_agent.add_tool(segment_urban_areas)
    zero_shot_cot_based_agent.add_tool(segment_individual_buildings)
    zero_shot_cot_based_agent.add_tool(segment_agricultural_fields)
    zero_shot_cot_based_agent.add_tool(classify_landscape_type)
    zero_shot_cot_based_agent.add_tool(classify_terrain_type)
    zero_shot_cot_based_agent.add_tool(assess_urbanization_level)
    zero_shot_cot_based_agent.add_tool(enhance_image_resolution)
    zero_shot_cot_based_agent.add_tool(detect_urban_expansion)
    zero_shot_cot_based_agent.add_tool(monitor_deforestation)
    zero_shot_cot_based_agent.add_tool(assess_disaster_damage)
    zero_shot_cot_based_agent.add_tool(explain_remote_sensing_concepts)
    zero_shot_cot_based_agent.add_tool(recommend_satellite_platforms)
    zero_shot_cot_based_agent.add_tool(suggest_processing_workflows)
    zero_shot_cot_based_agent.add_tool(provide_technical_guidance)
    zero_shot_cot_based_agent.add_tool(monitor_crop_health)
    zero_shot_cot_based_agent.add_tool(predict_crop_yield)
    zero_shot_cot_based_agent.add_tool(detect_plant_diseases)
    zero_shot_cot_based_agent.add_tool(assess_soil_moisture)
    zero_shot_cot_based_agent.add_tool(optimize_irrigation_schedule)
    zero_shot_cot_based_agent.add_tool(assess_pasture_quality)
    zero_shot_cot_based_agent.add_tool(predict_harvest_timing)
    zero_shot_cot_based_agent.add_tool(analyze_farming_patterns)
    zero_shot_cot_based_agent.add_tool(monitor_flood_extent)
    zero_shot_cot_based_agent.add_tool(track_wildfire_progression)
    zero_shot_cot_based_agent.add_tool(assess_earthquake_damage)
    zero_shot_cot_based_agent.add_tool(predict_landslide_risk)
    zero_shot_cot_based_agent.add_tool(monitor_drought_conditions)
    zero_shot_cot_based_agent.add_tool(evaluate_infrastructure_damage)
    zero_shot_cot_based_agent.add_tool(plan_evacuation_routes)
    zero_shot_cot_based_agent.add_tool(assess_recovery_progress)
    zero_shot_cot_based_agent.add_tool(analyze_urban_growth_patterns)
    zero_shot_cot_based_agent.add_tool(assess_land_use_efficiency)
    zero_shot_cot_based_agent.add_tool(monitor_traffic_congestion)
    zero_shot_cot_based_agent.add_tool(evaluate_green_space_distribution)
    zero_shot_cot_based_agent.add_tool(assess_air_quality_patterns)
    zero_shot_cot_based_agent.add_tool(analyze_population_density)
    zero_shot_cot_based_agent.add_tool(evaluate_urban_heat_island)
    zero_shot_cot_based_agent.add_tool(assess_flood_risk_zones)
    zero_shot_cot_based_agent.add_tool(monitor_air_pollution)
    zero_shot_cot_based_agent.add_tool(assess_water_quality)
    zero_shot_cot_based_agent.add_tool(track_biodiversity_changes)
    zero_shot_cot_based_agent.add_tool(monitor_forest_health)
    zero_shot_cot_based_agent.add_tool(detect_illegal_logging)
    zero_shot_cot_based_agent.add_tool(assess_wetland_conditions)
    zero_shot_cot_based_agent.add_tool(evaluate_ecosystem_services)
    zero_shot_cot_based_agent.add_tool(assess_carbon_sequestration)
    zero_shot_cot_based_agent.add_tool(analyze_geological_structures)
    zero_shot_cot_based_agent.add_tool(identify_mineral_deposits)
    zero_shot_cot_based_agent.add_tool(assess_slope_stability)
    zero_shot_cot_based_agent.add_tool(map_fault_systems)
    zero_shot_cot_based_agent.add_tool(evaluate_groundwater_resources)
    zero_shot_cot_based_agent.add_tool(assess_volcanic_activity)
    zero_shot_cot_based_agent.add_tool(explore_mineral_resources)
    zero_shot_cot_based_agent.add_tool(monitor_mining_operations)
    zero_shot_cot_based_agent.add_tool(assess_environmental_impact)
    zero_shot_cot_based_agent.add_tool(track_land_reclamation)
    zero_shot_cot_based_agent.add_tool(evaluate_ore_quality)
    zero_shot_cot_based_agent.add_tool(assess_mining_safety)
    zero_shot_cot_based_agent.add_tool(monitor_sea_surface_temperature)
    zero_shot_cot_based_agent.add_tool(track_ocean_currents)
    zero_shot_cot_based_agent.add_tool(assess_marine_pollution)
    zero_shot_cot_based_agent.add_tool(monitor_algae_blooms)
    zero_shot_cot_based_agent.add_tool(track_ship_movements)
    zero_shot_cot_based_agent.add_tool(assess_coastal_erosion)
    zero_shot_cot_based_agent.add_tool(monitor_ice_coverage)
    zero_shot_cot_based_agent.add_tool(evaluate_fishing_grounds)
    zero_shot_cot_based_agent.add_tool(detect_military_facilities)
    zero_shot_cot_based_agent.add_tool(monitor_border_security)
    zero_shot_cot_based_agent.add_tool(assess_strategic_infrastructure)
    zero_shot_cot_based_agent.add_tool(track_vessel_activities)
    zero_shot_cot_based_agent.add_tool(monitor_airspace_violations)
    zero_shot_cot_based_agent.add_tool(analyze_threat_patterns)
    zero_shot_cot_based_agent.add_tool(assess_force_deployment)
    zero_shot_cot_based_agent.add_tool(evaluate_operational_readiness)
    return zero_shot_cot_based_agent

def create_debate_agent(model="gpt-4o-mini",api_key=os.getenv("OPENAI_API_KEY"),base_url=os.getenv("OPENAI_API_BASE")):
    debate_agent = DebateAgent(model=model,api_key=api_key,base_url=base_url)
    debate_agent.add_tool_to_debater(download_file)
    debate_agent.add_tool_to_debater(web_search)
    debate_agent.add_tool_to_debater(get_weather_data)
    debate_agent.add_tool_to_debater(statistical_analysis)
    debate_agent.add_tool_to_debater(linear_regression)
    debate_agent.add_tool_to_debater(correlation_analysis)
    debate_agent.add_tool_to_debater(convert_coordinates)
    debate_agent.add_tool_to_debater(format_data)
    debate_agent.add_tool_to_debater(read_database)
    debate_agent.add_tool_to_debater(get_current_time)
    debate_agent.add_tool_to_debater(calculate_time_difference)
    debate_agent.add_tool_to_debater(extract_keywords)
    debate_agent.add_tool_to_debater(translate_text)
    debate_agent.add_tool_to_debater(summarize_text)
    debate_agent.add_tool_to_debater(resize_image)
    debate_agent.add_tool_to_debater(crop_image)
    debate_agent.add_tool_to_debater(extract_image_metadata)
    debate_agent.add_tool_to_debater(download_satellite_imagery)
    debate_agent.add_tool_to_debater(atmospheric_correction)
    debate_agent.add_tool_to_debater(geometric_correction)
    debate_agent.add_tool_to_debater(cloud_mask_removal)
    debate_agent.add_tool_to_debater(band_combination)
    debate_agent.add_tool_to_debater(detect_buildings)
    debate_agent.add_tool_to_debater(detect_roads)
    debate_agent.add_tool_to_debater(detect_vehicles)
    debate_agent.add_tool_to_debater(detect_ships)
    debate_agent.add_tool_to_debater(classify_land_cover)
    debate_agent.add_tool_to_debater(segment_vegetation)
    debate_agent.add_tool_to_debater(segment_water_bodies)
    debate_agent.add_tool_to_debater(segment_urban_areas)
    debate_agent.add_tool_to_debater(segment_individual_buildings)
    debate_agent.add_tool_to_debater(segment_agricultural_fields)
    debate_agent.add_tool_to_debater(classify_landscape_type)
    debate_agent.add_tool_to_debater(classify_terrain_type)
    debate_agent.add_tool_to_debater(assess_urbanization_level)
    debate_agent.add_tool_to_debater(enhance_image_resolution)
    debate_agent.add_tool_to_debater(detect_urban_expansion)
    debate_agent.add_tool_to_debater(monitor_deforestation)
    debate_agent.add_tool_to_debater(assess_disaster_damage)
    debate_agent.add_tool_to_debater(explain_remote_sensing_concepts)
    debate_agent.add_tool_to_debater(recommend_satellite_platforms)
    debate_agent.add_tool_to_debater(suggest_processing_workflows)
    debate_agent.add_tool_to_debater(provide_technical_guidance)
    debate_agent.add_tool_to_debater(monitor_crop_health)
    debate_agent.add_tool_to_debater(predict_crop_yield)
    debate_agent.add_tool_to_debater(detect_plant_diseases)
    debate_agent.add_tool_to_debater(assess_soil_moisture)
    debate_agent.add_tool_to_debater(optimize_irrigation_schedule)
    debate_agent.add_tool_to_debater(assess_pasture_quality)
    debate_agent.add_tool_to_debater(predict_harvest_timing)
    debate_agent.add_tool_to_debater(analyze_farming_patterns)
    debate_agent.add_tool_to_debater(monitor_flood_extent)
    debate_agent.add_tool_to_debater(track_wildfire_progression)
    debate_agent.add_tool_to_debater(assess_earthquake_damage)
    debate_agent.add_tool_to_debater(predict_landslide_risk)
    debate_agent.add_tool_to_debater(monitor_drought_conditions)
    debate_agent.add_tool_to_debater(evaluate_infrastructure_damage)
    debate_agent.add_tool_to_debater(plan_evacuation_routes)
    debate_agent.add_tool_to_debater(assess_recovery_progress)
    debate_agent.add_tool_to_debater(analyze_urban_growth_patterns)
    debate_agent.add_tool_to_debater(assess_land_use_efficiency)
    debate_agent.add_tool_to_debater(monitor_traffic_congestion)
    debate_agent.add_tool_to_debater(evaluate_green_space_distribution)
    debate_agent.add_tool_to_debater(assess_air_quality_patterns)
    debate_agent.add_tool_to_debater(analyze_population_density)
    debate_agent.add_tool_to_debater(evaluate_urban_heat_island)
    debate_agent.add_tool_to_debater(assess_flood_risk_zones)
    debate_agent.add_tool_to_debater(monitor_air_pollution)
    debate_agent.add_tool_to_debater(assess_water_quality)
    debate_agent.add_tool_to_debater(track_biodiversity_changes)
    debate_agent.add_tool_to_debater(monitor_forest_health)
    debate_agent.add_tool_to_debater(detect_illegal_logging)
    debate_agent.add_tool_to_debater(assess_wetland_conditions)
    debate_agent.add_tool_to_debater(evaluate_ecosystem_services)
    debate_agent.add_tool_to_debater(assess_carbon_sequestration)
    debate_agent.add_tool_to_debater(analyze_geological_structures)
    debate_agent.add_tool_to_debater(identify_mineral_deposits)
    debate_agent.add_tool_to_debater(assess_slope_stability)
    debate_agent.add_tool_to_debater(map_fault_systems)
    debate_agent.add_tool_to_debater(evaluate_groundwater_resources)
    debate_agent.add_tool_to_debater(assess_volcanic_activity)
    debate_agent.add_tool_to_debater(explore_mineral_resources)
    debate_agent.add_tool_to_debater(monitor_mining_operations)
    debate_agent.add_tool_to_debater(assess_environmental_impact)
    debate_agent.add_tool_to_debater(track_land_reclamation)
    debate_agent.add_tool_to_debater(evaluate_ore_quality)
    debate_agent.add_tool_to_debater(assess_mining_safety)
    debate_agent.add_tool_to_debater(monitor_sea_surface_temperature)
    debate_agent.add_tool_to_debater(track_ocean_currents)
    debate_agent.add_tool_to_debater(assess_marine_pollution)
    debate_agent.add_tool_to_debater(monitor_algae_blooms)
    debate_agent.add_tool_to_debater(track_ship_movements)
    debate_agent.add_tool_to_debater(assess_coastal_erosion)
    debate_agent.add_tool_to_debater(monitor_ice_coverage)
    debate_agent.add_tool_to_debater(evaluate_fishing_grounds)
    debate_agent.add_tool_to_debater(detect_military_facilities)
    debate_agent.add_tool_to_debater(monitor_border_security)
    debate_agent.add_tool_to_debater(assess_strategic_infrastructure)
    debate_agent.add_tool_to_debater(track_vessel_activities)
    debate_agent.add_tool_to_debater(monitor_airspace_violations)
    debate_agent.add_tool_to_debater(analyze_threat_patterns)
    debate_agent.add_tool_to_debater(assess_force_deployment)
    debate_agent.add_tool_to_debater(evaluate_operational_readiness)
    return debate_agent

def create_aflow_agent():
    aflow_agent = AFlowAgent()
    aflow_agent.add_tool(download_file)
    aflow_agent.add_tool(web_search)
    aflow_agent.add_tool(get_weather_data)
    aflow_agent.add_tool(statistical_analysis)
    aflow_agent.add_tool(linear_regression)
    aflow_agent.add_tool(correlation_analysis)
    aflow_agent.add_tool(convert_coordinates)
    aflow_agent.add_tool(format_data)
    aflow_agent.add_tool(read_database)
    aflow_agent.add_tool(get_current_time)
    aflow_agent.add_tool(calculate_time_difference)
    aflow_agent.add_tool(extract_keywords)
    aflow_agent.add_tool(translate_text)
    aflow_agent.add_tool(summarize_text)
    aflow_agent.add_tool(resize_image)
    aflow_agent.add_tool(crop_image)
    aflow_agent.add_tool(extract_image_metadata)
    aflow_agent.add_tool(download_satellite_imagery)
    aflow_agent.add_tool(atmospheric_correction)
    aflow_agent.add_tool(geometric_correction)
    aflow_agent.add_tool(cloud_mask_removal)
    aflow_agent.add_tool(band_combination)
    aflow_agent.add_tool(detect_buildings)
    aflow_agent.add_tool(detect_roads)
    aflow_agent.add_tool(detect_vehicles)
    aflow_agent.add_tool(detect_ships)
    aflow_agent.add_tool(classify_land_cover)
    aflow_agent.add_tool(segment_vegetation)
    aflow_agent.add_tool(segment_water_bodies)
    aflow_agent.add_tool(segment_urban_areas)
    aflow_agent.add_tool(segment_individual_buildings)
    aflow_agent.add_tool(segment_agricultural_fields)
    aflow_agent.add_tool(classify_landscape_type)
    aflow_agent.add_tool(classify_terrain_type)
    aflow_agent.add_tool(assess_urbanization_level)
    aflow_agent.add_tool(enhance_image_resolution)
    aflow_agent.add_tool(detect_urban_expansion)
    aflow_agent.add_tool(monitor_deforestation)
    aflow_agent.add_tool(assess_disaster_damage)
    aflow_agent.add_tool(explain_remote_sensing_concepts)
    aflow_agent.add_tool(recommend_satellite_platforms)
    aflow_agent.add_tool(suggest_processing_workflows)
    aflow_agent.add_tool(provide_technical_guidance)
    aflow_agent.add_tool(monitor_crop_health)
    aflow_agent.add_tool(predict_crop_yield)
    aflow_agent.add_tool(detect_plant_diseases)
    aflow_agent.add_tool(assess_soil_moisture)
    aflow_agent.add_tool(optimize_irrigation_schedule)
    aflow_agent.add_tool(assess_pasture_quality)
    aflow_agent.add_tool(predict_harvest_timing)
    aflow_agent.add_tool(analyze_farming_patterns)
    aflow_agent.add_tool(monitor_flood_extent)
    aflow_agent.add_tool(track_wildfire_progression)
    aflow_agent.add_tool(assess_earthquake_damage)
    aflow_agent.add_tool(predict_landslide_risk)
    aflow_agent.add_tool(monitor_drought_conditions)
    aflow_agent.add_tool(evaluate_infrastructure_damage)
    aflow_agent.add_tool(plan_evacuation_routes)
    aflow_agent.add_tool(assess_recovery_progress)
    aflow_agent.add_tool(analyze_urban_growth_patterns)
    aflow_agent.add_tool(assess_land_use_efficiency)
    aflow_agent.add_tool(monitor_traffic_congestion)
    aflow_agent.add_tool(evaluate_green_space_distribution)
    aflow_agent.add_tool(assess_air_quality_patterns)
    aflow_agent.add_tool(analyze_population_density)
    aflow_agent.add_tool(evaluate_urban_heat_island)
    aflow_agent.add_tool(assess_flood_risk_zones)
    aflow_agent.add_tool(monitor_air_pollution)
    aflow_agent.add_tool(assess_water_quality)
    aflow_agent.add_tool(track_biodiversity_changes)
    aflow_agent.add_tool(monitor_forest_health)
    aflow_agent.add_tool(detect_illegal_logging)
    aflow_agent.add_tool(assess_wetland_conditions)
    aflow_agent.add_tool(evaluate_ecosystem_services)
    aflow_agent.add_tool(assess_carbon_sequestration)
    aflow_agent.add_tool(analyze_geological_structures)
    aflow_agent.add_tool(identify_mineral_deposits)
    aflow_agent.add_tool(assess_slope_stability)
    aflow_agent.add_tool(map_fault_systems)
    aflow_agent.add_tool(evaluate_groundwater_resources)
    aflow_agent.add_tool(assess_volcanic_activity)
    aflow_agent.add_tool(explore_mineral_resources)
    aflow_agent.add_tool(monitor_mining_operations)
    aflow_agent.add_tool(assess_environmental_impact)
    aflow_agent.add_tool(track_land_reclamation)
    aflow_agent.add_tool(evaluate_ore_quality)
    aflow_agent.add_tool(assess_mining_safety)
    aflow_agent.add_tool(monitor_sea_surface_temperature)
    aflow_agent.add_tool(track_ocean_currents)
    aflow_agent.add_tool(assess_marine_pollution)
    aflow_agent.add_tool(monitor_algae_blooms)
    aflow_agent.add_tool(track_ship_movements)
    aflow_agent.add_tool(assess_coastal_erosion)
    aflow_agent.add_tool(monitor_ice_coverage)
    aflow_agent.add_tool(evaluate_fishing_grounds)
    aflow_agent.add_tool(detect_military_facilities)
    aflow_agent.add_tool(monitor_border_security)
    aflow_agent.add_tool(assess_strategic_infrastructure)
    aflow_agent.add_tool(track_vessel_activities)
    aflow_agent.add_tool(monitor_airspace_violations)
    aflow_agent.add_tool(analyze_threat_patterns)
    aflow_agent.add_tool(assess_force_deployment)
    aflow_agent.add_tool(evaluate_operational_readiness)
    return aflow_agent

def create_arena():
    earth_agent = create_earth_agent()
    plan_and_execute_agent = create_plan_and_execute_agent()
    react_agent = create_react_agent()
    zero_shot_cot_based_agent = create_zero_shot_cot_based_agent()
    debate_agent = create_debate_agent()
    return earth_agent,plan_and_execute_agent,react_agent,zero_shot_cot_based_agent,debate_agent